export const LOAD_POKEMON_LIST = 'LOAD_POKEMON_LIST';
export const LOAD_POKEMON_LIST_SUCCESS = 'LOAD_POKEMON_LIST_SUCCESS';
export const LOAD_POKEMON_LIST_ERROR = 'LOAD_POKEMON_LIST_ERROR';

export const LOAD_POKEMON_DETAIL = 'LOAD_POKEMON_DETAIL';
export const LOAD_POKEMON_DETAIL_SUCCESS = 'LOAD_POKEMON_DETAIL_SUCCESS';
export const LOAD_POKEMON_DETAIL_ERROR = 'LOAD_POKEMON_DETAIL_ERROR';