export const LOAD_POKEMON_LIST = 'LOAD_POKEMON_LIST';
export const LOAD_POKEMON_LIST_SUCCESS = 'LOAD_POKEMON_LIST_SUCCESS';
export const LOAD_POKEMON_LIST_ERROR = 'LOAD_POKEMON_LIST_ERROR';

export const LOAD_POKEMON_DETAIL = 'LOAD_POKEMON_DETAIL';
export const LOAD_POKEMON_DETAIL_SUCCESS = 'LOAD_POKEMON_DETAIL_SUCCESS';
export const LOAD_POKEMON_DETAIL_ERROR = 'LOAD_POKEMON_DETAIL_ERROR';

export const CATCH_POKEMON = 'CATCH_POKEMON';
export const CATCH_POKEMON_SUCCESS = 'CATCH_POKEMON_SUCCESS';
export const CATCH_POKEMON_FAILED = 'CATCH_POKEMON_FAILED';
export const DELETE_POKEMON = 'DELETE_POKEMON';
